#ifndef UI_INTERNAL_H
#define UI_INTERNAL_H

#include "screen.h"

#define NORMAL_COLOR MAKECOLOR(COLOR_GREEN, COLOR_GRAY1)
#define INVERSE_COLOR MAKECOLOR(COLOR_GRAY1, COLOR_GREEN)
#define TRANSPARENT_COLOR MAKECOLOR(COLOR_BLACK, COLOR_BLACK)

#define LAYER_UI 1
#define LAYER_CELLS 0

#define SYMBOL_SPACE 0x20
#define SYMBOL_LATIN_CAPITAL_LETTER_A 0x41
#define SYMBOL_LATIN_SMALL_LETTER_A 0x01
#define SYMBOL_DIGIT_ZERO 0x30

#endif /* UI_INTERNAL_H */
